// flow-typed signature: 4920c29772bb55628bf93f0e4a949dba
// flow-typed version: <<STUB>>/react-router-transition_v0.0.6/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-transition'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-transition' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-transition/lib/react-router-transition' {
  declare module.exports: any;
}

declare module 'react-router-transition/src/ensureSpring' {
  declare module.exports: any;
}

declare module 'react-router-transition/src/index' {
  declare module.exports: any;
}

declare module 'react-router-transition/src/presets' {
  declare module.exports: any;
}

declare module 'react-router-transition/src/RouteTransition' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-transition/lib/react-router-transition.js' {
  declare module.exports: $Exports<'react-router-transition/lib/react-router-transition'>;
}
declare module 'react-router-transition/src/ensureSpring.js' {
  declare module.exports: $Exports<'react-router-transition/src/ensureSpring'>;
}
declare module 'react-router-transition/src/index.js' {
  declare module.exports: $Exports<'react-router-transition/src/index'>;
}
declare module 'react-router-transition/src/presets.js' {
  declare module.exports: $Exports<'react-router-transition/src/presets'>;
}
declare module 'react-router-transition/src/RouteTransition.jsx' {
  declare module.exports: $Exports<'react-router-transition/src/RouteTransition'>;
}
